import { Algorithm } from "app/util"

const cornersRaw = [
    { category: "U", name: "AB", algorithm: "[R' B' R:[U',R D R']]" },
    { category: "U", name: "AD", algorithm: "[R' D R U':[R' D' R , U']]" },
    { category: "U", name: "AF", algorithm: "[F: [U2, R' D' R]]" },
    { category: "U", name: "AG", algorithm: "[R' D R, U2]" },
    { category: "U", name: "AH", algorithm: "[U': [R D' R', U2]]" },
    { category: "U", name: "AI", algorithm: "[Lw': [U2, R' D2 R]]" },
    { category: "U", name: "AK", algorithm: "[D U': [R D R', U2]]" },
    { category: "U", name: "AL", algorithm: "[U' D': [R D' R', U2]]" },
    { category: "U", name: "AO", algorithm: "[U': [R D R', U2]]" },
    { category: "U", name: "AP", algorithm: "[R' D' R, U2]" },
    { category: "U", name: "AQ", algorithm: "[R' D': [U2, R' D R]]" },
    { category: "U", name: "AS", algorithm: "[R' D2 R, U2]" },
    { category: "U", name: "AT", algorithm: "[U' D: [R D' R', U2]]" },
    { category: "U", name: "AU", algorithm: "[R F' R' U': [R D R', U2]]" },
    { category: "U", name: "AV", algorithm: "[D R D' R': [R' D R, U2]]" },
    { category: "U", name: "AW", algorithm: "[R D' R': [R' D R, U2]]" },
    { category: "U", name: "AX", algorithm: "[D' R D' R': [R' D R, U2]]" },
    { category: "U", name: "BA", algorithm: "[Lw': [R' D2 R, U]]" },
    { category: "U", name: "BD", algorithm: "[Lw D: [R' D' R, U]]" },
    { category: "U", name: "BE", algorithm: "[R: [U, R D R']]" },
    { category: "U", name: "BF", algorithm: "[R': [R' D' R, U']]" },
    { category: "U", name: "BG", algorithm: "[R' D R, U]" },
    { category: "U", name: "BH", algorithm: "[U', R D' R']" },
    { category: "U", name: "BI", algorithm: "[R: [U2, R D R']]" },
    { category: "U", name: "BK", algorithm: "[D': [R' D R, U]]" },
    { category: "U", name: "BL", algorithm: "[D: [R' D' R, U]]" },
    { category: "U", name: "BO", algorithm: "[U', R D R']" },
    { category: "U", name: "BP", algorithm: "[R' D' R, U]" },
    { category: "U", name: "BR", algorithm: "[R': [R' D' R, U2]]" },
    { category: "U", name: "BS", algorithm: "[R' D2 R, U]" },
    { category: "U", name: "BT", algorithm: "[D: [U', R D' R']]" },
    { category: "U", name: "BU", algorithm: "[x': [D2, R U R']]" },
    { category: "U", name: "BV", algorithm: "[U' R' D R: [R D' R', U]]" },
    { category: "U", name: "BW", algorithm: "[U R D' R': [U', R' D R]]" },
    { category: "U", name: "BX", algorithm: "[x: [R' U' R, D2]]" },
    { category: "U", name: "DA", algorithm: "[R' D'U': [R' D R, U']]" },
    { category: "U", name: "DE", algorithm: "[U' R: [R D R', U2]]" },
    { category: "U", name: "DG", algorithm: "[R' D R, U']" },
    { category: "U", name: "DH", algorithm: "[U': [R D' R', U']]" },
    { category: "U", name: "DK", algorithm: "[D': [R' D R, U']]" },
    { category: "U", name: "DL", algorithm: "[D: [R' D' R, U']]" },
    { category: "U", name: "DN", algorithm: "[U' R': [U2, R' D' R]]" },
    { category: "U", name: "DO", algorithm: "[U': [R D R', U']]" },
    { category: "U", name: "DP", algorithm: "[R' D' R, U']" },
    { category: "U", name: "DQ", algorithm: "[U' R: [R D R', U]]" },
    { category: "U", name: "DR", algorithm: "[U' R': [U', R' D' R]]" },
    { category: "U", name: "DS", algorithm: "[R' D2 R, U']" },
    { category: "U", name: "DT", algorithm: "[D': [R' D' R, U']]" },
    { category: "U", name: "DU", algorithm: "[U' x': [R U R', D2]]" },
    { category: "U", name: "DV", algorithm: "[D R D' R': [R' D R, U']]" },
    { category: "U", name: "DW", algorithm: "[R D' R': [R' D R, U']]" },
    { category: "U", name: "DX", algorithm: "[R' D' R : [R U' R', D]]" },

    { category: "L", name: "EG", algorithm: "[U R' U': [R' D R, U]]" },
    { category: "L", name: "EH", algorithm: "[R D': [R D R', U]]" },
    { category: "L", name: "EI", algorithm: "[Lw' U: [R D' R', U2]]" },
    { category: "L", name: "EK", algorithm: "[R U R' : [R' D' R, U']]" },
    { category: "L", name: "EL", algorithm: "[R U: [R' D R, U]]" },
    { category: "L", name: "EN", algorithm: "[R: [R2' D R2 D' R2', U]]" },
    { category: "L", name: "EO", algorithm: "[R D: [R D R', U]]" },
    { category: "L", name: "EP", algorithm: "[D' R U : [R' D R, U]]" },
    { category: "L", name: "EQ", algorithm: "[U R': [U', R' D' R]]" },
    { category: "L", name: "ES", algorithm: "[U R': [U', R' D2 R]]" },
    { category: "L", name: "ET", algorithm: "[R U: [R' D' R, U]]" },
    { category: "L", name: "EU", algorithm: "[R: [R D2 R', U]]" },
    { category: "L", name: "EV", algorithm: "[D2 R: [R D' R', U]]" },
    { category: "L", name: "EW", algorithm: "[D R: [R D' R', U]]" },
    { category: "L", name: "EX", algorithm: "[R: [R D' R', U]]" },
    { category: "L", name: "FG", algorithm: "[R' U' : [D, R U R']]" },
    { category: "L", name: "FH", algorithm: "[z: [R' D' R, U2]]" },
    { category: "L", name: "FK", algorithm: "[R, U L U']" },
    { category: "L", name: "FL", algorithm: "[D R' U': [D', R U R']]" },
    { category: "L", name: "FN", algorithm: "[F' U: [R' D R, U2]]" },
    { category: "L", name: "FO", algorithm: "[R' U': [R' D' R, U2]]" },
    { category: "L", name: "FP", algorithm: "[R' U': [D', R U R']]" },
    { category: "L", name: "FQ", algorithm: "[R', U L U']" },
    { category: "L", name: "FR", algorithm: "[x': [R U' R', D]]" },
    { category: "L", name: "FS", algorithm: "[x': [R U2 R', D]]" },
    { category: "L", name: "FT", algorithm: "[F: [D', R U R']]" },
    { category: "L", name: "FU", algorithm: "[U' R' U: [R U' R', D]]" },
    { category: "L", name: "FV", algorithm: "[R U' R': [R' D' R, U2]]" },
    { category: "L", name: "FW", algorithm: "[z: [D2, R U R']]" },
    { category: "L", name: "FX", algorithm: "[R2 D2: [R U' R', D]]" },
    { category: "L", name: "GH", algorithm: "[z': [R U' R', D']]" },
    { category: "L", name: "GI", algorithm: "[D R': [F2, R D' R' D]]" },
    { category: "L", name: "GK", algorithm: "[U: [D, R U' R']]" },
    { category: "L", name: "GN", algorithm: "[U R U: [R' D R, U2]]" },
    { category: "L", name: "GO", algorithm: "[DU: [R U' R', D2]]" },
    { category: "L", name: "GP", algorithm: "[U R' D: [R U' R', D2]]" },
    { category: "L", name: "GQ", algorithm: "[R' U: [R U' R', D]]" },
    { category: "L", name: "GR", algorithm: "[Lw U2: [R D' R', U]]" },
    { category: "L", name: "GS", algorithm: "[U D: [R U' R', D]]" },
    { category: "L", name: "GT", algorithm: "[R' U' R: [U2, R' D R]]" },
    { category: "L", name: "GV", algorithm: "[U D R D' : [U', R' D R]]" },
    { category: "L", name: "GW", algorithm: "[U R : [D, R U' R']]" },
    { category: "L", name: "GX", algorithm: "[F': [R U' R', D2]]" },
    { category: "L", name: "HI", algorithm: "[Lw': [U2, R' D R]]" },
    { category: "L", name: "HK", algorithm: "[U R U': [R D' R', U']]" },
    { category: "L", name: "HL", algorithm: "[D2: [R U R', D']]" },
    { category: "L", name: "HN", algorithm: "[U R: [R D' R', U2]]" },
    { category: "L", name: "HO", algorithm: "[R D': [R' U' R, D2]]" },
    { category: "L", name: "HP", algorithm: "[D2, R U R']" },
    { category: "L", name: "HQ", algorithm: "[U' L U, R]" },
    { category: "L", name: "HR", algorithm: "[U2 R: [R D' R', U]]" },
    { category: "L", name: "HT", algorithm: "[D': [D', R U R']]" },
    { category: "L", name: "HU", algorithm: "[R D R' D: [R U R', D2]]" },
    { category: "L", name: "HV", algorithm: "[D2 R: [R D' R', U']]" },
    { category: "L", name: "HW", algorithm: "[R D' R': [R' D R, U]]" },

    { category: "F", name: "IK", algorithm: "[R': [R D' R' D, F2]]" },
    { category: "F", name: "IL", algorithm: "[R U: [R' D R, U2]]" },
    { category: "F", name: "IN", algorithm: "[R' : [U', R2 D' R2 D R2]]" },
    { category: "F", name: "IO", algorithm: "[Lw' U': [R D R', U2]]" },
    { category: "F", name: "IP", algorithm: "[Lw': [R' D' R, U2]]" },
    { category: "F", name: "IQ", algorithm: "[R D' U: [R' D' R, U2]]" },
    { category: "F", name: "IR", algorithm: "[R U R' D': [U2, R' D R]]" },
    { category: "F", name: "IS", algorithm: "[D R' D : [F2, D' R D R']]" },
    { category: "F", name: "IT", algorithm: "[R U: [R' D' R, U2]]" },
    { category: "F", name: "IU", algorithm: "[R U D: [R' D' R, U2]]" },
    { category: "F", name: "IV", algorithm: "[D' R U D: [R' D' R, U2]]" },
    { category: "F", name: "IW", algorithm: "[D R: [R D' R', U2]]" },
    { category: "F", name: "IX", algorithm: "[R: [R D' R', U2]]" },
    { category: "F", name: "KL", algorithm: "[U L' U', R]" },
    { category: "F", name: "KN", algorithm: "[U' R' U: [R D R', U2]]" },
    { category: "F", name: "KO", algorithm: "[U: [R U' R', D']]" },
    { category: "F", name: "KQ", algorithm: "[D' R' U: [R U' R', D]]" },
    { category: "F", name: "KR", algorithm: "[R: [U' L' U, R]]" },
    { category: "F", name: "KS", algorithm: "[U: [R U' R', D2]]" },
    { category: "F", name: "KT", algorithm: "[D R D: [R' U' R, D2]]" },
    { category: "F", name: "KU", algorithm: "[R : [R' U R U', F2]]" },
    { category: "F", name: "KW", algorithm: "[U R D': [U', R' D R]]" },
    { category: "F", name: "KX", algorithm: "[z: [R U2 R', D]]" },
    { category: "F", name: "LN", algorithm: "[F' U: [R' D' R, U2]]" },
    { category: "F", name: "LO", algorithm: "[R D: [D, R' U' R]]" },
    { category: "F", name: "LP", algorithm: "[D, R U R']" },
    { category: "F", name: "LQ", algorithm: "[R', U L' U']" },
    { category: "F", name: "LR", algorithm: "[D x': [R U' R', D']]" },
    { category: "F", name: "LS", algorithm: "[D' R D': [R' U' R, D2]]" },
    { category: "F", name: "LT", algorithm: "[D: [R U R', D2]]" },
    { category: "F", name: "LV", algorithm: "[R U' R': [R' D R, U2]]" },
    { category: "F", name: "LW", algorithm: "[D R: [R D' R', U']]" },
    { category: "F", name: "LX", algorithm: "[Lw' D: [R' D' R, U']]" },

    { category: "R", name: "NO", algorithm: "[U R U': [R' D' R, U2]]" },
    { category: "R", name: "NP", algorithm: "[U' R' U' D: [R D' R', U2]]" },
    { category: "R", name: "NR", algorithm: "[U R: [U2, R D R']]" },
    { category: "R", name: "NS", algorithm: "[U' R' U': [R D' R', U2]]" },
    { category: "R", name: "NT", algorithm: "[U D R: [U2, R D' R']]" },
    { category: "R", name: "NU", algorithm: "[U' R': [R' D R, U2]]" },
    { category: "R", name: "NV", algorithm: "[U' D' R': [R' D R, U2]]" },
    { category: "R", name: "NW", algorithm: "[F': [U2, R D R']]" },
    { category: "R", name: "NX", algorithm: "[U'D R': [R' D R, U2]]" },
    { category: "R", name: "OP", algorithm: "[R D': [R' D R, U]]" },
    { category: "R", name: "OQ", algorithm: "[U' R U: [R' U' R, D]]" },
    { category: "R", name: "OR", algorithm: "[R' U: [R' D' R, U]]" },
    { category: "R", name: "OS", algorithm: "[U': [R' U' R, D']]" },
    { category: "R", name: "OU", algorithm: "[U' R': [R' D R, U]]" },
    { category: "R", name: "OV", algorithm: "[R U' D' R' : [R' D R, U2]]" },
    { category: "R", name: "OX", algorithm: "[R2 D2: [R U R', D]]" },
    { category: "R", name: "PQ", algorithm: "[R D: [R D' R', U']]" },
    { category: "R", name: "PR", algorithm: "[x': [R U' R', D']]" },
    { category: "R", name: "PS", algorithm: "[x': [R U2 R', D']]" },
    { category: "R", name: "PT", algorithm: "[R U R', D']" },
    { category: "R", name: "PU", algorithm: "[R D: [U, R' D' R]]" },
    { category: "R", name: "PW", algorithm: "[R U' R' D R: [U, R D' R']]" },
    { category: "R", name: "PX", algorithm: "[R: [R D' R', U']]" },

    { category: "B", name: "QR", algorithm: "[R, U' L' U]" },
    { category: "B", name: "QS", algorithm: "[R' U: [D2, R U' R']]" },
    { category: "B", name: "QT", algorithm: "[R U': [R' U R, D]]" },
    { category: "B", name: "QU", algorithm: "[U D R' U': [R U R', D']]" },
    { category: "B", name: "QV", algorithm: "[U R' U': [R U R', D']]" },
    { category: "B", name: "QW", algorithm: "[D R U': [R' U R, D']]" },
    { category: "B", name: "QX", algorithm: "[R U': [R' U R, D']]" },
    { category: "B", name: "RS", algorithm: "[U' R' U': [R D' R', U']]" },
    { category: "B", name: "RT", algorithm: "[R2 U : [R D R', U2]]" },
    { category: "B", name: "RU", algorithm: "[U' R': [R' D R, U']]" },
    { category: "B", name: "RV", algorithm: "[U' D' R': [R' D R, U']]" },
    { category: "B", name: "RW", algorithm: "[U R : [D', R U' R']]" },
    { category: "B", name: "RX", algorithm: "[U' D R': [R' D R, U']]" },
    { category: "B", name: "ST", algorithm: "[U': [R', U' L U]]" },
    { category: "B", name: "SU", algorithm: "[x': [D2, R U2 R']]" },
    { category: "B", name: "SV", algorithm: "[U'D' R': [R' D R, U]]" },
    { category: "B", name: "SW", algorithm: "[U R: [D2, R U' R']]" },
    { category: "B", name: "TU", algorithm: "[D' R: [R D' R', U']]" },
    { category: "B", name: "TV", algorithm: "[D' R D: [U, R' D' R]]" },
    { category: "B", name: "TX", algorithm: "[R U' D' : [D2, R' U R]]" },

    { category: "D", name: "UV", algorithm: "[U' R' F' : [R U' R', D']]" },
    { category: "D", name: "UW", algorithm: "[U' R2: [R2 U R2 U' R2, D]]" },
    { category: "D", name: "UX", algorithm: "[x U: [R' D R, U2]]" },
    { category: "D", name: "VW", algorithm: "[F' R U': [R' D' R, U2]]" },
    { category: "D", name: "VX", algorithm: "[R U' R' U: [R D' R', U2]]" },
    { category: "D", name: "WX", algorithm: "[z: [R U2 R', D2]]" },
]

export const corners: Algorithm[] = cornersRaw.map(c => new Algorithm(c.name, c.algorithm, c.category, true));
